name: Azure Contoso Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  validate:
    # Validate Azure Connection'
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Azure/infra
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Az CLI login
        uses: azure/login@v1
        with:
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          #allow-no-subscriptions: true

      - name: Logout
        run: |
          az logout
  devinfra:
    name: Dev Infra
    needs: Validate
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    defaults:
      run:
        shell: bash               
        working-directory: ./Azure/infra/terraform
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/contoso.tfvars"]'

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply tfplan.out

      - name: Terraform Output
        if: github.ref == 'refs/heads/main'
        run: |
          terraform output   